# -*- coding: utf-8 -*-
# list of dicts for individual glaciers, each dict must look like
# {'rgi_id': '', 'name': '', 'type': '', 'img': '', 'img_pretext': '', 'img_cite': '', 'img_license': '', 'img_license_link': '', 'img_width': '', 'img_height': '', 'img_source': ''}

glaciers = [{'rgi_id': 'RGI60-01.01104',
             'name': 'Lemon Creek Glacier',
             'type': 'Pure ice glacier',
             'img': 'https://raw.githubusercontent.com/pat-schmitt/glacier-gallery/adapt_data_handling/glacier_photos/lemoncreek.jpg',
             'img_pretext': 'Photo courtesy',
             'img_cite': 'L. Bernier/National Snow and Ice Data Center',
             'img_license': '',
             'img_license_link': '',
             'img_width': '390',
             'img_height': '260',
             'img_source': 'http://nsidc.org/data/glacier_photo/search/image_info/lemoncreek20070917'
             },

            {'rgi_id': 'RGI60-01.10689',
             'name': 'Columbia Glacier',
             'type': 'Calving glacier',
             'img': 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Columbia_Glacier_%28Alaska%29_by_Sentinel-2.jpg',
             'img_pretext': '',
             'img_cite': 'Photo contains modified Copernicus Sentinel-2 data, (European Space Agency - ESA)  2018',
             'img_license': '(CC BY-SA 3.0 IGO)',
             'img_license_link': 'https://creativecommons.org/licenses/by-sa/3.0/igo/deed.en',
             'img_width': '300',
             'img_height': '318',
             'img_source': 'https://commons.wikimedia.org/wiki/File:Columbia_Glacier_(Alaska)_by_Sentinel-2.jpg'
             },

            {'rgi_id': 'RGI60-03.04539',
             'name': 'White Glacier',
             'type': 'Pure ice glacier',
             'img': 'https://raw.githubusercontent.com/OGGM/glacier-gallery/master/glacier_photos/white.jpg',
             'img_pretext': 'Photo courtesy',
             'img_cite': 'J. Alean/National Snow and Ice Data Center',
             'img_license': '',
             'img_license_link': '',
             'img_width': '300',
             'img_height': '200',
             'img_source': 'http://nsidc.org/data/glacier_photo/search/image_info/white20080702'
            },

            {'rgi_id': 'RGI60-05.11186',
             'name': 'Mittivakkat Glacier',
             'type': 'Ice cap',
             'img': 'https://raw.githubusercontent.com/OGGM/glacier-gallery/master/glacier_photos/mittivakkat.jpg',
             'img_pretext': 'Photo courtesy',
             'img_cite': 'N. Knudsen/National Snow and Ice Data Center',
             'img_license': '',
             'img_license_link': '',
             'img_width': '400',
             'img_height': '300',
             'img_source': 'http://nsidc.org/data/glacier_photo/search/image_info/mittivakkat20130827?order=true'
            },

            {'rgi_id': 'RGI60-07.00570',
             'name': 'Nordenskioldbreen',
             'type': 'Calving glacier',
             'img': 'https://raw.githubusercontent.com/OGGM/glacier-gallery/master/glacier_photos/nordenskioldbreen.JPG',
             'img_pretext': 'Photo courtesy',
             'img_cite': 'H. Crites',
             'img_license': '',
             'img_license_link': '',
             'img_width': '300',
             'img_height': '225',
             'img_source': 'https://www.researchgate.net/publication/325218515_Drumlins_in_the_Nordenskioldbreen_forefield_Svalbard'
            },

            {'rgi_id': 'RGI60-08.01097',
             'name': 'Briksdalsbreen',
             'type': 'Pure ice glacier',
             'img': 'https://raw.githubusercontent.com/OGGM/glacier-gallery/master/glacier_photos/briksdalsbreen.jpg',
             'img_pretext': 'Photo courtesy',
             'img_cite': 'J. Perez Crespo/National Snow and Ice Data Center',
             'img_license': '(CC BY-NC)',
             'img_license_link': 'https://creativecommons.org/licenses/by-nc/4.0/',
             'img_width': '259',
             'img_height': '387',
             'img_source': 'http://nsidc.org/data/glacier_photo/search/image_info/briksdalsbreen20090730?order=true'
            },

            {'rgi_id': 'RGI60-11.00897',
             'name': 'Hintereisferner',
             'type': 'Pure ice glacier',
             'img': 'https://raw.githubusercontent.com/OGGM/glacier-gallery/master/glacier_photos/hintereisferner.bmp',
             'img_pretext': 'Photo courtesy',
             'img_cite': 'A. Lambrecht/National Snow and Ice Data Center',
             'img_license': '',
             'img_license_link': '',
             'img_width': '400',
             'img_height': '265',
             'img_source': 'http://nsidc.org/data/glacier_photo/search/image_info/hintereisferner20060912?order=true'
            },

            {'rgi_id': 'RGI60-11.01450',
             'name': 'Großer Aletschgletscher',
             'type': 'Pure ice glacier',
             'img': 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Grosser_Aletschgletscher_3196.JPG',
             'img_pretext': 'Photo courtesy',
             'img_cite': 'Dirk Beyer',
             'img_license': '(CC BY-SA 3.0)',
             'img_license_link': 'https://creativecommons.org/licenses/by-sa/3.0/',
             'img_width': '408',
             'img_height': '306',
             'img_source': 'https://commons.wikimedia.org/wiki/File:Grosser_Aletschgletscher_3196.JPG'
            },

            {'rgi_id': 'RGI60-12.00411',
             'name': 'Tbilisa Glacier',
             'type': 'Pure ice glacier',
             'img': 'https://raw.githubusercontent.com/OGGM/glacier-gallery/master/glacier_photos/tbilisa.jpg',
             'img_pretext': 'Photo courtesy',
             'img_cite': 'L. Tielidze/National Snow and Ice Data Center',
             'img_license': '',
             'img_license_link': '',
             'img_width': '360',
             'img_height': '272',
             'img_source': 'http://nsidc.org/data/glacier_photo/search/image_info/tbilisa20109999'
            },

            {'rgi_id': 'RGI60-15.03733',
             'name': 'Khumbu Glacier',
             'type': 'Debris covered glacier',
             'img': 'https://raw.githubusercontent.com/OGGM/glacier-gallery/master/glacier_photos/khumbu.JPG',
             'img_pretext': 'Photo courtesy',
             'img_cite': 'Z. Schirmeister',
             'img_license': '',
             'img_license_link': '',
             'img_width': '400',
             'img_height': '300',
             'img_source': ''
            },

            {'rgi_id': 'RGI60-16.01638',
             'name': 'Lewis',
             'type': 'Pure ice glacier',
             'img': 'https://raw.githubusercontent.com/OGGM/glacier-gallery/master/glacier_photos/lewis.jpg',
             'img_pretext': 'Photo courtesy',
             'img_cite': 'R. Prinz/National Snow and Ice Data Center',
             'img_license': '',
             'img_license_link': '',
             'img_width': '400',
             'img_height': '300',
             'img_source': 'http://nsidc.org/data/glacier_photo/search/image_info/lewis20120223'
            },

            {'rgi_id': 'RGI60-16.02444',
             'name': 'Artesonraju',
             'type': 'Pure ice glacier',
             'img': 'https://upload.wikimedia.org/wikipedia/commons/0/06/Artesonraju_Peru.jpg',
             'img_pretext': 'Photo courtesy',
             'img_cite': 'Jonas Jancarik',
             'img_license': '(CC BY 3.0)',
             'img_license_link': 'https://creativecommons.org/licenses/by/3.0/deed.en',
             'img_width': '400',
             'img_height': '276',
             'img_source': 'https://commons.wikimedia.org/wiki/File:Artesonraju_Peru.jpg'
            },

            {'rgi_id': 'RGI60-17.00312',
             'name': 'Perito Moreno',
             'type': 'Calving glacier',
             'img': 'https://raw.githubusercontent.com/OGGM/glacier-gallery/master/glacier_photos/peritomoreno.jpg',
             'img_pretext': '',
             'img_cite': 'Imagery from International Space Station, courtesy Earth Science and Remote Sensing Unit, NASA Johnson Space Center',
             'img_license': '',
             'img_license_link': '',
             'img_width': '400',
             'img_height': '272',
             'img_source': 'https://eol.jsc.nasa.gov/SearchPhotos/photo.pl?mission=ISS016&roll=E&frame=24897'
            },

            {'rgi_id': 'RGI60-18.02342',
             'name': 'Tasman Glacier',
             'type': 'Debris covered glacier',
             'img': 'https://upload.wikimedia.org/wikipedia/commons/8/87/Lower_Tasman_Glacier_towards_Minarets.jpg',
             'img_pretext': '',
             'img_cite': '',
             'img_license': '(released into public domain by holder of the work)',
             'img_license_link': '',
             'img_width': '400',
             'img_height': '266',
             'img_source': 'https://commons.wikimedia.org/wiki/File:Lower_Tasman_Glacier_towards_Minarets.jpg'
            },

            {'rgi_id': 'RGI60-19.00595',
             'name': 'Bahia Del Diablo Glacier',
             'type': 'Pure ice glacier',
             'img': 'https://raw.githubusercontent.com/OGGM/glacier-gallery/master/glacier_photos/bahiadeldiablo.bmp',
             'img_pretext': 'Photo courtesy',
             'img_cite': 'P. Skvarca/National Snow and Ice Data Center',
             'img_license': '',
             'img_license_link': '',
             'img_width': '400',
             'img_height': '260',
             'img_source': 'http://nsidc.org/data/glacier_photo/search/image_info/bahiadeldiablo20040224'
            },

             ]

# More glacier suggestions:
              #('RGI60-09.00114', 'Severny Island Ice Cap', np.NaN, np.NaN, '', ''),
              #('RGI60-09.00471', 'Vavilov Ice Cap', np.NaN, np.NaN,  '', ''),
              #('RGI60-13.04946', 'Samoilowich', np.NaN, np.NaN, '', ''), 
              #('RGI60-19.00386', 'Ross Island', '', '', ''),
